<a href="https://colab.research.google.com/github/impashree/CSE/blob/main/Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

importing libraies

In [5]:
import numpy as np
import pandas as pd

importing the dataset

In [6]:
df=pd.read_csv('Data.csv')
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values
print(x)
print()
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


filling the missing values

In [8]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(x[:,1:3])
x[:,1:3]=imputer.transform (x[:,1:3])
print(x)


[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


Encoding the independent variable

In [9]:
from sklearn .compose import ColumnTransformer
from sklearn .preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoders',OneHotEncoder(),[0])],remainder='passthrough')
x=np.array(ct.fit_transform(x))
print(x)
     


[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


Encoding Dependent variable

In [10]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


splitting the dataset into train and test set

In [11]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=1)


feature scaling 

In [12]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
xtrain[:,:3]=sc.fit_transform(xtrain[:,:3])
xtest[:,:3]=sc.fit_transform(xtest[:,:3])
print(xtrain)
print(xtest)

[[-0.7745966692414834 -0.5773502691896258 1.2909944487358056
  38.77777777777778 52000.0]
 [-0.7745966692414834 1.7320508075688774 -0.7745966692414834 40.0
  63777.77777777778]
 [1.2909944487358056 -0.5773502691896258 -0.7745966692414834 44.0 72000.0]
 [-0.7745966692414834 -0.5773502691896258 1.2909944487358056 38.0 61000.0]
 [-0.7745966692414834 -0.5773502691896258 1.2909944487358056 27.0 48000.0]
 [1.2909944487358056 -0.5773502691896258 -0.7745966692414834 48.0 79000.0]
 [-0.7745966692414834 1.7320508075688774 -0.7745966692414834 50.0 83000.0]
 [1.2909944487358056 -0.5773502691896258 -0.7745966692414834 35.0 58000.0]]
[[-1.0 1.0 0.0 30.0 54000.0]
 [1.0 -1.0 0.0 37.0 67000.0]]
